### ISSUE TITLE
Ensembl mapping pipeline for annotation source code

### ISSUE THREAD

**Issue by 5Tony** [human-pangenomics/hpp_production_workflows#19] opened 2023-05-12 03:08 UTC
Hi all,
I want to use the **Ensembl Mapping Pipeline for annation** in this paper ([A draft human pangenome reference](https://www.nature.com/articles/s41586-023-05896-x)) , but I could not find the source codes in this repository. Is this pipeline not publicly available? Or am I missing something?
There is only a description of the process and some code in the [paper](https://www.nature.com/articles/s41586-023-05896-x), but I can't use the Ensembl Mapping Pipeline for annation method.

Thanks!

Best,
Tony

**Comment by juklucas** [comment] 2023-05-15 19:36
duplicate of [this issue](https://github.com/human-pangenomics/hpp_production_workflows/issues/17).

**Closed by juklucas** 2023-05-15 19:36 UTC
